apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-04-27T21:27:36Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: task-api
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-04-27T21:27:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-27T21:27:43Z"
  name: task-api
  namespace: default
  resourceVersion: "29481"
  selfLink: /api/v1/namespaces/default/services/task-api
  uid: 672dbf80-3fba-4d9f-a6a9-93a86a54e10b
spec:
  clusterIP: 10.0.203.167
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32166
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.67.120.120
